### ISSUE TITLE
jquery combobox lose it selected value on form submit

### ISSUE THREAD

**Issue by mahboob-awan** [bseth99/jquery-ui-extensions#1]
Widget does not populate selected value after form submit.

If you look at http://www.learningjquery.com/2010/06/a-jquery-ui-combobox-under-the-hood  

```
  var select = this.element.hide(),
  selected = select.children( ":selected" ),
  value = selected.val() ? selected.text() : "";
```

that is use to handle this issue. But i did not find the same handling within your extension.

**Comment by mahboob-awan** [comment]
And i used the following steps as work-around:

1 - Comment following line:
https://github.com/bseth99/jquery-ui-extensions/blob/master/ui/jquery.ui.combobox.js#L52
2 - 
 $('selector').combobox({
    create:function(e,ui){
            $(this).data('ui-combobox').uiInput.val($(e.target).find(':selected').text());
   }
});

But Waiting for a good solution within this plugin. Thanks

**Comment by bseth99** [comment]
You're solution was on the right path.  I removed the line that clears the select element and then ensured the autocomplete input was preloaded with the text from the select box on page load.  Now, when you use the demo, you can select a state, refresh the page, and it will load the value.
